config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'contacts#new'
  
  resources :users, only: [:index, :show]
  resources :contacts, only: [:new, :create]
  resources :users do
    get '/one_day', to: 'static_pages#one_day'
    get '/calendar', to: 'static_pages#calendar'
    get '/mon_menus', to: 'static_pages#mon_menus'
    get '/tue_menus', to: 'static_pages#tue_menus'
    get '/wed_menus', to: 'static_pages#wed_menus'
    get '/thu_menus', to: 'static_pages#thu_menus'
    get '/fri_menus', to: 'static_pages#fri_menus'
    get '/sat_menus', to: 'static_pages#sat_menus'
    get '/sun_menus', to: 'static_pages#sun_menus'
    resources :items
    get '/items_search', to: 'items#search'
    resources :menus
    resources :menus do
      resources :menu_items, only: [:index, :create]
      get 'menu_items/dynamic_items', to: 'menu_items#dynamic_items'
      delete '/menu_items', to: 'menu_items#destroy_all'
    end
    resources :week_menus, only: [:index, :create]
    delete '/week_menus', to: 'week_menus#destroy_all'
    resources :menu_records, only: [:update]
    delete '/menu_records', to: 'menu_records#destroy_all'
    resources :item_records, only: [:update]
    patch '/item_records', to: 'item_records#update_all'
  end
  
  # サンプル用の一時的なルーティング
  get '/one_day', to: 'sample_pages#one_day'
  get '/calendar', to: 'sample_pages#calendar'
  get '/mon_menus', to: 'sample_pages#mon_menus'
  get '/tue_menus', to: 'sample_pages#tue_menus'
  get '/wed_menus', to: 'sample_pages#wed_menus'
  get '/thu_menus', to: 'sample_pages#thu_menus'
  get '/fri_menus', to: 'sample_pages#fri_menus'
  get '/sat_menus', to: 'sample_pages#sat_menus'
  get '/sun_menus', to: 'sample_pages#sun_menus'
  get '/week_menus', to: 'sample_pages#week_menus'
  get '/menus', to: 'sample_pages#menus'
  get '/new_menu', to: 'sample_pages#new_menu'
  get '/menu', to: 'sample_pages#menu'
  get '/edit_menu', to: 'sample_pages#edit_menu'
  get '/menu_items', to: 'sample_pages#menu_items'
  get 'menu_items/dynamic_items', to: 'sample_pages#dynamic_items'
  get '/items', to: 'sample_pages#items'
  get '/items_search', to: 'sample_pages#search'
  get '/new_item', to: 'sample_pages#new_item'
  get '/item', to: 'sample_pages#item'
  get '/edit_item', to: 'sample_pages#edit_item'
  get '/sample_user', to: 'sample_pages#sample_user'
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :user
  has_many :week_menus, dependent: :destroy
  has_many :menu_items, dependent: :destroy
  validates :name, presence: true, length: { maximum: 15 }
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  
  def index
    @menus = current_user.menus.page(params[:page]).per(10)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @menu = Menu.find(params[:id])
    @menu_items = @menu.menu_items
  end

  def new
    @menu = Menu.new
  end
  
  def create
    @menu = current_user.menus.build(menu_params)
    if @menu.save
      redirect_to user_menu_menu_items_url(current_user, @menu)
    else
      render 'new'
    end
  end

  def edit
    @menu = Menu.find(params[:id])
  end
  
  def update
    @menu = Menu.find(params[:id])
    if @menu.update(menu_params)
      flash[:success] = "メニュー名を更新しました。"
      redirect_to user_menu_url(current_user)
    else
      render 'edit'
    end
  end
  
  def destroy
    Menu.find(params[:id]).destroy
    flash[:success] = "メニューを削除しました。"
    redirect_to user_menus_url(current_user)
  end
  
  private

    def menu_params
      params.require(:menu).permit(:name)
    end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_index_page.html.erb
<div class="list-group list">
  <% @menus.each do |menu| %>
   <%= link_to menu.name, user_menu_path(current_user, menu), class: "list-group-item list-group-item-action" %>
  <% end %>
</div>
<%= paginate @menus, remote: true %>

app/views/menus/edit.html.erb
<% provide(:title, "メニュー名の編集") %>
<h1 class="mb-3">メニュー名の編集</h1>

<div class="row row-original">
  <div class="col-md-6 col-md-6-original">
    <%= 
      form_with model: @menu,
      url: user_menu_path(current_user),
      local: true do |f|
    %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="form-group">
        <%= f.label :name %>
        <%= 
          f.text_field :name,
          autofocus: true,
          autocomplete: 'name',
          class: 'form-control'
        %>
      </div>
      <div class="form-group pt-3 mb-0">
        <%= f.submit "更新", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

<div class="link-center mt-2rem">
  <i class="fas fa-angle-double-left"></i>
  <%= 
    link_to "メニューへ戻る",
    user_menu_path(current_user, @menu),
    class: "link-center icon-edit"
  %>
</div>

app/views/menus/index.html.erb
<% provide(:title, "メニュー一覧") %>
<h1 class="mb-3">メニュー一覧</h1>

<div class="link-center mb-3">
  <i class="far fa-plus-square"></i>
  <%= 
    link_to "新規作成",
    new_user_menu_path,
    class: "link-center icon-edit"
  %>
</div>

<div id="menus">
  <div class="list-group list">
    <% @menus.each do |menu| %>
     <%= link_to menu.name,
       user_menu_path(current_user, menu),
       class: "list-group-item list-group-item-action"
     %>
    <% end %>
  </div>
<%= paginate @menus, remote: true %>
</div>

app/views/menus/index.js.erb
$('#menus').html("<%= escape_javascript(render 'index_page') %>");

app/views/menus/new.html.erb
<% provide(:title, "メニュー作成") %>
<h1 class="mb-3">メニュー作成</h1>

<div class="row row-original">
  <div class="col-md-6 col-md-6-original">
    <p class="text-center">まずはメニュー名を決めてください。</p>
    <%= form_with model: @menu, url: user_menus_path(current_user), local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true, autocomplete: 'name', class: 'form-control' %>
      </div>
      <div class="form-group pt-3 mb-0">
        <%= f.submit "次へ", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>    

<div class="link-center mt-2rem">
  <i class="fas fa-angle-double-left"></i>
  <%= 
    link_to "メニュー一覧へ戻る",
    user_menus_path(current_user),
    class: "link-center icon-edit"
  %>
</div>

app/views/menus/show.html.erb
<% provide(:title, @menu.name) %>
<h1 class="mb-3 text-center"><%= @menu.name %></h1>
<div class="link-center">
  <i class="fas fa-pencil-alt"></i>
  <%= 
    link_to "メニュー名を編集",
    edit_user_menu_path(current_user, @menu),
    class: "link-center icon-edit"
  %>&nbsp;&nbsp;/&nbsp;<i class="fas fa-pencil-alt"></i>
  <%= 
    link_to "メニュー内容を編集",
    user_menu_menu_items_path(current_user, @menu),
    class: "link-center icon-reset"
  %>&nbsp;&nbsp;/&nbsp;<i class="far fa-minus-square"></i>
  <%= 
    link_to "メニューを削除",
    user_menu_path(current_user, @menu),
    class: "link-center icon-reset",
    method: :delete,
    data: { confirm: "本当にメニューを削除しますか？" }
  %>
</div>

<div class="text-center">
  <div class="menu-items-list">
    <% if @menu_items.present? %>
      <ul>
        <% @menu_items.each do |menu_item| %>
          <li><%= menu_item.item.name %>
            <div class="item-details">
              <% if menu_item.weight.present? %>
                <span>
                  <%= menu_item.weight %><small class="unit">kg</small>
                </span>
              <% end %>
              <% if menu_item.reps.present? %>
                <span>
                  <%= menu_item.reps %><small class="unit">回</small>
                </span>
              <% end %>
              <% if menu_item.seconds.present? %>
                <span>
                  <%= menu_item.seconds %><small class="unit">秒</small>
                </span>
              <% end %>
              <% if menu_item.sets.present? %>
                <span>
                  <%= menu_item.sets %><small class="unit">セット</small>
                </span>
              <% end %>
            </div>
          </li>
        <% end %>
      </ul>
    <% else %>
      <div class="menu-message">
        <span>メニュー内容は未登録です。</span>
      </div>
    <% end %>
  </div>
  
  <div class="link-center mt-3">
    <i class="fas fa-angle-double-left"></i>
    <%= 
      link_to "メニュー一覧へ戻る",
      user_menus_path(current_user),
      class: "link-center icon-edit"
    %>
  </div>
</div>