config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'contacts#new'
  
  resources :users, only: [:index, :show]
  resources :contacts, only: [:new, :create]
  resources :users do
    get '/one_day', to: 'static_pages#one_day'
    get '/calendar', to: 'static_pages#calendar'
    get '/mon_menus', to: 'static_pages#mon_menus'
    get '/tue_menus', to: 'static_pages#tue_menus'
    get '/wed_menus', to: 'static_pages#wed_menus'
    get '/thu_menus', to: 'static_pages#thu_menus'
    get '/fri_menus', to: 'static_pages#fri_menus'
    get '/sat_menus', to: 'static_pages#sat_menus'
    get '/sun_menus', to: 'static_pages#sun_menus'
    resources :items
    get '/items_search', to: 'items#search'
    resources :menus
    resources :menus do
      resources :menu_items, only: [:index, :create]
      get 'menu_items/dynamic_items', to: 'menu_items#dynamic_items'
      delete '/menu_items', to: 'menu_items#destroy_all'
    end
    resources :week_menus, only: [:index, :create]
    delete '/week_menus', to: 'week_menus#destroy_all'
    resources :menu_records, only: [:update]
    delete '/menu_records', to: 'menu_records#destroy_all'
    resources :item_records, only: [:update]
    patch '/item_records', to: 'item_records#update_all'
  end
  
  # サンプル用の一時的なルーティング
  get '/one_day', to: 'sample_pages#one_day'
  get '/calendar', to: 'sample_pages#calendar'
  get '/mon_menus', to: 'sample_pages#mon_menus'
  get '/tue_menus', to: 'sample_pages#tue_menus'
  get '/wed_menus', to: 'sample_pages#wed_menus'
  get '/thu_menus', to: 'sample_pages#thu_menus'
  get '/fri_menus', to: 'sample_pages#fri_menus'
  get '/sat_menus', to: 'sample_pages#sat_menus'
  get '/sun_menus', to: 'sample_pages#sun_menus'
  get '/week_menus', to: 'sample_pages#week_menus'
  get '/menus', to: 'sample_pages#menus'
  get '/new_menu', to: 'sample_pages#new_menu'
  get '/menu', to: 'sample_pages#menu'
  get '/edit_menu', to: 'sample_pages#edit_menu'
  get '/menu_items', to: 'sample_pages#menu_items'
  get 'menu_items/dynamic_items', to: 'sample_pages#dynamic_items'
  get '/items', to: 'sample_pages#items'
  get '/items_search', to: 'sample_pages#search'
  get '/new_item', to: 'sample_pages#new_item'
  get '/item', to: 'sample_pages#item'
  get '/edit_item', to: 'sample_pages#edit_item'
  get '/sample_user', to: 'sample_pages#sample_user'
end

app/controllers/sample_pages_controller.rb
class SamplePagesController < ApplicationController
  
  def one_day
    @user = User.find(2)
    @date = params[:date].to_date
    @cwday = @date.cwday
    @week_menus = @user.week_menus.where(cwday: @cwday)
    @menu_records = @user.menu_records.where(date: @date)
    if @date > Date.today
      @message = "この日はお休みです。"
    elsif @date == Date.today
      @message = "今日はお休みです。"
    else
      @message = "この日はお休みでした。"
    end
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def calendar
    @user = User.find(2)
    @menu_records = @user.menu_records
                      .where(checked: true)
                        .where.not(date: Date.today)
    respond_to do |format|
     format.html
     format.json { render 'calendar', handlers: 'jbuilder' }
    end
  end
  
  def mon_menus
    @user = User.find(2)
    @mon_menus = @user.week_menus.where(cwday: 1)
    respond_to do |format|
     format.json { render 'mon_menus', handlers: 'jbuilder' }
    end
  end
  
  def tue_menus
    @user = User.find(2)
    @tue_menus = @user.week_menus.where(cwday: 2)
    respond_to do |format|
     format.json { render 'tue_menus', handlers: 'jbuilder' }
    end
  end
  
  def wed_menus
    @user = User.find(2)
    @wed_menus = @user.week_menus.where(cwday: 3)
    respond_to do |format|
     format.json { render 'wed_menus', handlers: 'jbuilder' }
    end
  end
  
  def thu_menus
    @user = User.find(2)
    @thu_menus = @user.week_menus.where(cwday: 4)
    respond_to do |format|
     format.json { render 'thu_menus', handlers: 'jbuilder' }
    end
  end
  
  def fri_menus
    @user = User.find(2)
    @fri_menus = @user.week_menus.where(cwday: 5)
    respond_to do |format|
     format.json { render 'fri_menus', handlers: 'jbuilder' }
    end
  end
  
  def sat_menus
    @user = User.find(2)
    @sat_menus = @user.week_menus.where(cwday: 6)
    respond_to do |format|
     format.json { render 'sat_menus', handlers: 'jbuilder' }
    end
  end
  
  def sun_menus
    @user = User.find(2)
    @sun_menus = @user.week_menus.where(cwday: 7)
    respond_to do |format|
     format.json { render 'sun_menus', handlers: 'jbuilder' }
    end
  end
  
  def week_menus
    @user = User.find(2)
    @week_menus = WeekMenuCollection.new
    @week_menus.collection = []
    1.upto(7) do |i|
      attributes = []
      attributes[i] = @user.week_menus.where(cwday: i)
      if attributes[i].any?
        day_menus = WeekMenuCollection.new(attributes[i])
      else
        day_menus = WeekMenuCollection.new
      end
      @week_menus.collection.concat(day_menus.collection)
    end
  end
  
  def menus
    @user = User.find(2)
    @menus = @user.menus.page(params[:page]).per(10)
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def new_menu
    @menu = Menu.new
  end
  
  def menu
    @menu = Menu.find(params[:menu_id])
    @menu_items = @menu.menu_items
  end
  
  def edit_menu
    @menu = Menu.find(params[:menu_id])
  end
  
  def menu_items
    @user = User.find(2)
    @menu = Menu.find(params[:menu_id])
    @items = Item.where(default: true)
              .or(Item.where(user_id: @user.id))
                .order("name")
    attributes = []
    attributes = @user.menus.find(params[:menu_id]).menu_items
    if attributes.any?
      @menu_items = MenuItemCollection.new(attributes)
    else
      @menu_items = MenuItemCollection.new
    end
    # 部位・タイプのセレクトボックスに使う配列を生成する
    prompt = [
              ["部位・タイプで選ぶ", 
               data: {
                 children_path: menu_items_dynamic_items_path
               }
              ],
              ["全て",
                data: {
                 children_path: menu_items_dynamic_items_path
                }
              ]
             ]
    parts = [["---- 部位 ----",
              data: {
                children_path: menu_items_dynamic_items_path
              }
            ]] +
            Part.order(:id).map {
              |p| [p.name, data: {
                children_path: menu_items_dynamic_items_path(part_id: p.id)
                }
              ]
            }
    types = [["---- タイプ ----",
              data: {
                children_path: menu_items_dynamic_items_path
                }
            ]] +
            Type.order(:id).map {
              |t| [t.name, data: {
                children_path: menu_items_dynamic_items_path(type_id: t.id)
                }
              ]
            }
    @parts_types = prompt + parts + types
  end
  
  def dynamic_items
    @user = User.find(2)
    # ユーザーの選択に応じてjsの動作を分ける
    if params[:part_id]
      part = Part.find(params[:part_id])
      render json: Item.where(default: true, part_id: part.id)
                    .or(Item.where(user_id: @user.id, part_id: part.id))
                      .order("name").select(:id, :name)
    elsif params[:type_id]
      type = Type.find(params[:type_id])
      render json: Item.where(default: true, type_id: type.id)
                    .or(Item.where(user_id: @user.id, type_id: type.id))
                      .order("name").select(:id, :name)
    else
      render json: Item.where(default: true)
                    .or(Item.where(user_id: @user.id))
                      .order("name").select(:id, :name) 
    end
  end
  
  def items
    @user = User.find(2)
    @items = Item.where(default: true)
              .or(Item.where(user_id: @user.id))
                .order("name").page(params[:page]).per(10)
    respond_to do |format|
      format.html
      format.js
    end
    # 部位・タイプのプルダウンに使う配列を生成する
    prompt = [["部位・タイプで探す"], ["全て"]]
    parts = [["---- 部位 ----"]] + Part.order(:id).map { |p| [p.name] }
    types = [["---- タイプ ----"]] + Type.order(:id).map { |t| [t.name] }
    @parts_types = prompt + parts + types
  end
  
  def search
    @user = User.find(2)
    # プルダウンの選択に応じてインスタンス変数に種目一覧を代入する
    if part = Part.find_by(name: params[:parts_types])
      @items = Item.where(default: true, part_id: part.id)
                .or(Item.where(user_id: @user.id, part_id: part.id))
                  .order("name").page(params[:page]).per(10)
    elsif type = Type.find_by(name: params[:parts_types])
      @items = Item.where(default: true, type_id: type.id)
                .or(Item.where(user_id: @user.id, type_id: type.id))
                  .order("name").page(params[:page]).per(10)
    else
      @items = Item.where(default: true)
                .or(Item.where(user_id: @user.id))
                  .order("name").page(params[:page]).per(10)
    end
  end
  
  def new_item
    @item = Item.new
    @parts = Part.all
    @types = Type.all
  end
  
  def item
    @user = User.find(2)
    @item = Item.find(params[:item_id])
    @part = Part.find(@item.part_id)
    @type = Type.find(@item.type_id)
  end
  
  def edit_item
    @item = Item.find(params[:item_id])
    @parts = Part.all
    @types = Type.all
  end
  
  def sample_user
    @user = User.find(2)
  end
end

app/helpers/sample_pages_helper.rb
module SamplePagesHelper
end

app/views/sample_pages/_menu_item_form.html.erb
<td>
  <div class="parts-types">
    <%= 
      select_tag "parts_types",
      options_for_select(parts_types),
      :class => "custom-select select-parent",
      :id => "parts_types#{count}"
    %>
  </div>
  <div class="items">
    <%=
      field.collection_select :item_id,
      items,
      :id,
      :name,
      {:include_blank => true},
      :class => "custom-select select-children",
      :id => "menu_items_item_id#{count}"
    %>
  </div>
</td>
<td class="relative" data-label="重量">
  <%=
    field.number_field :weight,
    min: '1',
    max: '999',
    class: 'form-control',
    id: "menu_items_weight#{count}"
  %>
  <small class="unit"><b>kg</b></small>
</td>
<td class="relative" data-label="回数">
  <%=
    field.number_field :reps,
    min: '1',
    max: '999',
    class: 'form-control',
    id: "menu_items_reps#{count}"
  %>
  <small class="unit"><b>回</b></small>
</td>
<td class="relative" data-label="秒数">
  <%=
    field.number_field :seconds,
    min: '1',
    max: '999',
    class: 'form-control',
    id: "menu_items_seconds#{count}"
  %>
  <small class="unit"><b>秒</b></small>
<td class="relative" data-label="セット数">
  <%=
    field.number_field :sets,
    min: '1',
    max: '999',
    class: 'form-control',
    id: "menu_items_sets#{count}"
  %>
  <small class="unit"><b>セット</b></small>
</td>
<td>
  <button type="button" class="btn btn-link btn-reset" style="display: none;">
    <i class="fas fa-times"></i>
  </button>
</td>

app/views/sample_pages/_records_exist.html.erb
<p class="text-center mb-2rem">達成率： <span id="rate">0</span>%</p>

<div class="records row justify-content-center">
  <% menu_count = 0 %>
  <% item_count = 0 %>
  <% @menu_records.each do |menu_record| %>
    <% menu_count += 1 %>
    <% if (item_records = menu_record.item_records).present? %>
      <div class="top-menu col-sm-12 col-md-4">
        <h2 class="mb-2"><%= menu_record.name %></h2>
        <div class="top-itembox">
          <div class="top-itemlist">
            <% item_records.each do |item_record| %>
              <% item_count += 1 %>
              <%= 
                form_with url: "#" do |f|
              %>
                <%=
                  f.check_box :checked,
                  id: "customCheck#{menu_count}_#{item_count}",
                  :as => :boolean
                %>
                <%=
                  f.label item_record.name,
                  for: "customCheck#{menu_count}_#{item_count}"
                %>
                <div class="item-details">
                  <% if item_record.weight.present? %>
                    <span>
                      <%= item_record.weight %><small class="unit">kg</small>
                    </span>
                  <% end %>
                  <% if item_record.reps.present? %>
                    <span>
                      <%= item_record.reps %><small class="unit">回</small>
                    </span>
                  <% end %>
                  <% if item_record.seconds.present? %>
                    <span>
                      <%= item_record.seconds %><small class="unit">秒</small>
                    </span>
                  <% end %>
                  <% if item_record.sets.present? %>
                    <span>
                      <%= item_record.sets %><small class="unit">セット</small>
                    </span>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="check-uncheck">
          <div class="all-check">
            <%= 
              link_to " 全てチェック",
              "#",
              class: "link-center icon check btn-outline-original",
              remote: true
            %>
          </div>
          <div class="all-uncheck">
            <%= 
              link_to " 全てアンチェック",
              "#",
              class: "link-center icon uncheck btn-outline-original",
              remote: true
            %>
          </div>
        </div>
      </div>
    <% else %>
      <div class="col-sm-12 col-md-4">
        <div class="menu-only">
          <div class="menu-label">
            <%= 
              form_with url: "#" do |f|
            %>
              <%=
                f.check_box :checked,
                id: "customCheck#{menu_count}",
                :as => :boolean
              %>
              <%=
                f.label :checked,
                class: "menu-only-label",
                for: "customCheck#{menu_count}" do
              %>
                <span><%= menu_record.name %></span>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="top-itembox message-box">
          <div class="menu-message">
            <span>メニュー内容は未登録です。</span>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/sample_pages/_week_menu_form.html.erb
<% number = 0 %>
<% day_menus.each do |day_menu| %>
  <% number += 1 %>
  <%= fields_for 'week_menus[]', day_menu do |field| %>
    <%=
      field.collection_select :menu_id,
      @user.menus,
      :id,
      :name,
      {:include_blank => true},
      {:class => "custom-select", :id => "week_menus#{count}_#{number}"}
    %>
  <% end %>
<% end %>

app/views/sample_pages/calendar.html.erb
<% provide(:title, "カレンダー") %>
<h1 class="mb-3 text-center">カレンダー（サンプル）</h1>

<div id="calendar"></div>

app/views/sample_pages/edit_item.html.erb
<% provide(:title, "種目の編集") %>
<h1 class="mb-3 text-center">種目の編集（サンプル）</h1>

<div class="row row-original">
  <div class="col-md-6 col-md-6-original">
    <%= 
      form_with url: "#" do |f|
    %>
      <div class="form-group">
        <%= f.label "種目名" %>
        <%= 
          f.text_field :name,
          autofocus: true,
          autocomplete: 'name',
          class: 'form-control'
        %>
      </div>
      <div class="form-group">
        <%= f.label "メイン部位", for: 'item_part_id' %>
        <%= 
          f.collection_select :part_id, @parts, :id, :name,
          {:include_blank => true},
          {:class => "custom-select"}
        %>
      </div>
      <div class="form-group">
        <%= f.label "タイプ", for: 'item_type_id' %>
        <%= 
          f.collection_select :type_id, @types, :id, :name,
          {:include_blank => true},
          {:class => "custom-select"}
        %>
      </div>
      <div class="form-group pt-3 mb-0">
        <%= f.submit "更新（要ログイン）", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

<div class="link-center mt-2rem">
  <i class="fas fa-angle-double-left"></i>
  <%= 
    link_to "種目へ戻る",
    item_path(item_id: @item.id),
    class: "link-center icon-edit"
  %>
</div>

app/views/sample_pages/item.html.erb
<% provide(:title, @item.name) %>
<h1 class="mb-3 text-center"><%= @item.name %>（サンプル）</h1>

<% if @item.user_id == @user.id %>
  <div class="link-center">
    <i class="fas fa-pencil-alt"></i>
    <%= link_to "編集",
      edit_item_path(item_id: @item.id),
      class: "link-center icon-edit"
    %>&nbsp;&nbsp;/&nbsp;<i class="far fa-minus-square"></i>
    <%= 
      link_to "種目を削除（要ログイン）",
      "#",
      class: "link-center icon-reset",
      data: { confirm: "本当に種目を削除しますか？" }
    %>
  </div>
<% end %>

<table class="tbl-r02">
  <tr>
    <th>種目名</th>
    <td><%= @item.name %></td>
  </tr>
  <tr>
    <th>メイン部位</th>
    <td><%= @part.name %></td>
  </tr>
  <tr class="last">
    <th>タイプ</th>
    <td><%= @type.name %></td>
  </tr>
</table>

<div class="link-center">
  <i class="fas fa-angle-double-left"></i>
  <%= 
    link_to "種目一覧へ戻る",
    items_path,
    class: "link-center icon-edit"
  %>
</div>

app/views/sample_pages/items.html.erb
<% provide(:title, "種目一覧") %>
<h1 class="mb-3">種目一覧（サンプル）</h1>

<div class="link-center mb-3">
  <i class="far fa-plus-square"></i>
  <%= 
    link_to "新規作成",
    new_item_path,
    class: "link-center icon-edit"
  %>
</div>

<div class="parts-types select-search">
  <%=
    form_with url: items_search_path,
    method: :get,
    class: "search-form" do |f|
  %>
    <%= 
      f.select "parts_types", 
      @parts_types,
      {},
      class: "custom-select select-parts-types"
    %>
  <% end %>
</div>

<div id="items">
<div class="list-group list">
  <% @items.each do |item| %>
   <%= link_to item.name,
     item_path(item_id: item.id),
     class: "list-group-item list-group-item-action"
   %>
  <% end %>
</div>
<%= paginate @items, remote: true %>
</div>

app/views/sample_pages/items.js.erb
$('#items').html("<%= escape_javascript(render 'items_page') %>");

app/views/sample_pages/menu.html.erb
<% provide(:title, @menu.name) %>
<h1 class="mb-3 text-center"><%= @menu.name %>（サンプル）</h1>
<div class="link-center">
  <i class="fas fa-pencil-alt"></i>
  <%= 
    link_to "メニュー名を編集",
    edit_menu_path(menu_id: @menu.id),
    class: "link-center icon-edit"
  %>&nbsp;&nbsp;/&nbsp;<i class="fas fa-pencil-alt"></i>
  <%= 
    link_to "メニュー内容を編集",
    menu_items_path(menu_id: @menu.id),
    class: "link-center icon-reset"
  %>&nbsp;&nbsp;/&nbsp;<i class="far fa-minus-square"></i>
  <%= 
    link_to "メニューを削除（要ログイン）",
    "#",
    class: "link-center icon-reset",
    data: { confirm: "本当にメニューを削除しますか？" }
  %>
</div>

<div class="text-center">
  <div class="menu-items-list">
    <% if @menu_items.present? %>
      <ul>
        <% @menu_items.each do |menu_item| %>
          <li><%= menu_item.item.name %>
            <div class="item-details">
              <% if menu_item.weight.present? %>
                <span>
                  <%= menu_item.weight %><small class="unit">kg</small>
                </span>
              <% end %>
              <% if menu_item.reps.present? %>
                <span>
                  <%= menu_item.reps %><small class="unit">回</small>
                </span>
              <% end %>
              <% if menu_item.seconds.present? %>
                <span>
                  <%= menu_item.seconds %><small class="unit">秒</small>
                </span>
              <% end %>
              <% if menu_item.sets.present? %>
                <span>
                  <%= menu_item.sets %><small class="unit">セット</small>
                </span>
              <% end %>
            </div>
          </li>
        <% end %>
      </ul>
    <% else %>
      <div class="menu-message">
        <span>メニュー内容は未登録です。</span>
      </div>
    <% end %>
  </div>
  
  <div class="link-center mt-3">
    <i class="fas fa-angle-double-left"></i>
    <%= 
      link_to "メニュー一覧へ戻る",
      menus_path,
      class: "link-center icon-edit"
    %>
  </div>
</div>

app/views/sample_pages/menus.js.erb
$('#menus').html("<%= escape_javascript(render 'menus_page') %>");

app/views/sample_pages/new_item.html.erb
<% provide(:title, "種目作成") %>
<h1 class="mb-3 text-center">種目作成（サンプル）</h1>

<div class="row row-original">
  <div class="col-md-6 col-md-6-original">
    <%= 
      form_with url: "#" do |f|
    %>
      <div class="form-group">
        <%= f.label "種目名" %>
        <%= 
          f.text_field :name,
          autofocus: true,
          autocomplete: 'name',
          class: 'form-control'
        %>
      </div>
      <div class="form-group">
        <%= f.label "メイン部位", for: 'item_part_id' %>
        <%= 
          f.collection_select :part_id, @parts, :id, :name,
          {:include_blank => true},
          {:class => "custom-select"}
        %>
      </div>
      <div class="form-group">
        <%= f.label "タイプ", for: 'item_type_id' %>
        <%= 
          f.collection_select :type_id, @types, :id, :name,
          {:include_blank => true},
          {:class => "custom-select"}
        %>
      </div>
      <div class="form-group pt-3 mb-0">
        <%= f.submit "作成（要ログイン）", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

<div class="link-center mt-2rem">
  <i class="fas fa-angle-double-left"></i>
  <%= 
    link_to "種目一覧へ戻る",
    items_path,
    class: "link-center icon-edit"
  %>
</div>

app/views/sample_pages/new_menu.html.erb
<% provide(:title, "メニュー作成") %>
<h1 class="mb-3">メニュー作成（サンプル）</h1>

<div class="row row-original">
  <div class="col-md-6 col-md-6-original">
    <p class="text-center">まずはメニュー名を決めてください。</p>
    <%= form_with url: "#" do |f| %>
      <div class="form-group">
        <%= f.label "メニュー名" %>
        <%= f.text_field :name, autofocus: true, autocomplete: 'name', class: 'form-control' %>
      </div>
      <div class="form-group pt-3 mb-0">
        <%= f.submit "次へ（要ログイン）", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>    

<div class="link-center mt-2rem">
  <i class="fas fa-angle-double-left"></i>
  <%= 
    link_to "メニュー一覧へ戻る",
    menus_path,
    class: "link-center icon-edit"
  %>
</div>

app/views/sample_pages/sample_user.html.erb
<% provide(:title, @user.name) %>
<h1 class="mb-3"><%= @user.name %>（サンプル）</h1>

<div class="user-data">
  <p class="text-center mb-0">Body</p>
  <ul class="users">
    <li>
      <div class="list-left">身長</div>
      <% if @user.height.present? %>
        <div class="list-right"><%= @user.height %>cm</div>
      <% else %>
        <div class="list-right">未設定</div>
      <% end %>
    </li>
    <li>
      <div class="list-left">体重</div>
      <% if @user.body_weight.present? %>
        <div class="list-right"><%= @user.body_weight %>kg</div>
      <% else %>
        <div class="list-right">未設定</div>
      <% end %>
    </li>
    <li>
      <div class="list-left">体脂肪率</div>
      <% if @user.body_fat.present? %>
        <div class="list-right"><%= @user.body_fat %>%</div>
      <% else %>
        <div class="list-right">未設定</div>
      <% end %>
    </li>
  </ul>
  <p class="text-center mt-3 mb-0">Max</p>
  <ul class="users">
    <li>
      <div class="list-left">ベンチプレス</div>
      <% if @user.bench_press.present? %>
        <div class="list-right"><%= @user.bench_press %>kg</div>
      <% else %>
        <div class="list-right">未設定</div>
      <% end %>
    </li>
    <li>
      <div class="list-left">スクワット</div>
      <% if @user.squat.present? %>
        <div class="list-right"><%= @user.squat %>kg</div>
      <% else %>
        <div class="list-right">未設定</div>
      <% end %>
    </li>
    <li>
      <div class="list-left">デッドリフト</div>
      <% if @user.deadlift.present? %>
        <div class="list-right"><%= @user.deadlift %>kg</div>
      <% else %>
        <div class="list-right">未設定</div>
      <% end %>
    </li>
  </ul>
</div>

app/views/sample_pages/week_menus.html.erb
<% provide(:title, "スケジュール管理") %>
<h1 class="mb-3">スケジュール管理（サンプル）</h1>
<div class="link-center mb-3">
  <i class="fas fa-eraser"></i>
  <%= link_to "リセット（要ログイン）",
    "#",
    class: "link-center icon-reset",
    data: { confirm: "本当にスケジュールをリセットしますか？" }
  %>
</div>

<%= 
  form_with url: "#",
  :html => {:class => "cont"} do |f|
%>
  <div class="cont">
    <% day = ["月", "火", "水", "木", "金", "土", "日"] %>
    <% count = 0 %>
    <% @week_menus.collection.each_slice(3) do |day_menus| %>
      <% count += 1 %>
      <% if count <= 5 %>
        <div class="item">
          <p class="weekday text-white mb-3"><%= day[(count - 1)] %></p>
          <%= render 'week_menu_form', day_menus: day_menus, count: count %>
        </div>
      <% elsif count == 6 %>
        <div class="item">
          <p class="saturday text-white mb-3"><%= day[(count - 1)] %></p>
          <%= render 'week_menu_form', day_menus: day_menus, count: count %>
        </div>
      <% else %>
        <div class="item">
          <p class="sunday text-white mb-3"><%= day[(count - 1)] %></p>
          <%= render 'week_menu_form', day_menus: day_menus, count: count %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-submit">
    <%= f.submit "更新（要ログイン）", class: 'btn btn-primary' %>
  </div>
<% end %>