config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'contacts#new'
  
  resources :users, only: [:index, :show]
  resources :contacts, only: [:new, :create]
  resources :users do
    get '/one_day', to: 'static_pages#one_day'
    get '/calendar', to: 'static_pages#calendar'
    get '/mon_menus', to: 'static_pages#mon_menus'
    get '/tue_menus', to: 'static_pages#tue_menus'
    get '/wed_menus', to: 'static_pages#wed_menus'
    get '/thu_menus', to: 'static_pages#thu_menus'
    get '/fri_menus', to: 'static_pages#fri_menus'
    get '/sat_menus', to: 'static_pages#sat_menus'
    get '/sun_menus', to: 'static_pages#sun_menus'
    resources :items
    get '/items_search', to: 'items#search'
    resources :menus
    resources :menus do
      resources :menu_items, only: [:index, :create]
      get 'menu_items/dynamic_items', to: 'menu_items#dynamic_items'
      delete '/menu_items', to: 'menu_items#destroy_all'
    end
    resources :week_menus, only: [:index, :create]
    delete '/week_menus', to: 'week_menus#destroy_all'
    resources :menu_records, only: [:update]
    delete '/menu_records', to: 'menu_records#destroy_all'
    resources :item_records, only: [:update]
    patch '/item_records', to: 'item_records#update_all'
  end
  
  # サンプル用の一時的なルーティング
  get '/one_day', to: 'sample_pages#one_day'
  get '/calendar', to: 'sample_pages#calendar'
  get '/mon_menus', to: 'sample_pages#mon_menus'
  get '/tue_menus', to: 'sample_pages#tue_menus'
  get '/wed_menus', to: 'sample_pages#wed_menus'
  get '/thu_menus', to: 'sample_pages#thu_menus'
  get '/fri_menus', to: 'sample_pages#fri_menus'
  get '/sat_menus', to: 'sample_pages#sat_menus'
  get '/sun_menus', to: 'sample_pages#sun_menus'
  get '/week_menus', to: 'sample_pages#week_menus'
  get '/menus', to: 'sample_pages#menus'
  get '/new_menu', to: 'sample_pages#new_menu'
  get '/menu', to: 'sample_pages#menu'
  get '/edit_menu', to: 'sample_pages#edit_menu'
  get '/menu_items', to: 'sample_pages#menu_items'
  get 'menu_items/dynamic_items', to: 'sample_pages#dynamic_items'
  get '/items', to: 'sample_pages#items'
  get '/items_search', to: 'sample_pages#search'
  get '/new_item', to: 'sample_pages#new_item'
  get '/item', to: 'sample_pages#item'
  get '/edit_item', to: 'sample_pages#edit_item'
  get '/sample_user', to: 'sample_pages#sample_user'
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :part
  belongs_to :type
  has_many :menu_items, dependent: :destroy
  validates :name, presence: true, length: { maximum: 30 }
  validates :user_id, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def index
    @items = Item.where(default: true)
              .or(Item.where(user_id: current_user.id))
                .order("name").page(params[:page]).per(10)
    respond_to do |format|
      format.html
      format.js
    end
    # 部位・タイプのプルダウンに使う配列を生成する
    prompt = [["部位・タイプで探す"], ["全て"]]
    parts = [["---- 部位 ----"]] + Part.order(:id).map { |p| [p.name] }
    types = [["---- タイプ ----"]] + Type.order(:id).map { |t| [t.name] }
    @parts_types = prompt + parts + types
  end
  
  def search
    # プルダウンの選択に応じてインスタンス変数に種目一覧を代入する
    if part = Part.find_by(name: params[:parts_types])
      @items = Item.where(default: true, part_id: part.id)
                .or(Item.where(user_id: current_user.id, part_id: part.id))
                  .order("name").page(params[:page]).per(10)
    elsif type = Type.find_by(name: params[:parts_types])
      @items = Item.where(default: true, type_id: type.id)
                .or(Item.where(user_id: current_user.id, type_id: type.id))
                  .order("name").page(params[:page]).per(10)
    else
      @items = Item.where(default: true)
                .or(Item.where(user_id: current_user.id))
                  .order("name").page(params[:page]).per(10)
    end
  end
  
  def show
    @item = Item.find(params[:id])
    @part = Part.find(@item.part_id)
    @type = Type.find(@item.type_id)
  end

  def new
    @item = Item.new
    @parts = Part.all
    @types = Type.all
  end
  
  def create
    @item = current_user.items.build(item_params)
    if @item.save
      flash[:success] = "種目を作成しました。"
      redirect_to user_item_url(current_user, @item)
    else
      @parts = Part.all
      @types = Type.all
      render 'new'
    end
  end

  def edit
    @item = Item.find(params[:id])
    @parts = Part.all
    @types = Type.all
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:success] = "種目を更新しました。"
      redirect_to user_item_url(current_user)
    else
      render 'edit'
    end
  end
  
  def destroy
    Item.find(params[:id]).destroy
    flash[:success] = "種目を削除しました。"
    redirect_to user_items_url(current_user)
  end
  
  private
  
    def item_params
      params.require(:item).permit(:name, :part_id, :type_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_index_page.html.erb
<div class="list-group list">
  <% @items.each do |item| %>
   <%= 
     link_to item.name,
     user_item_path(current_user, item),
     class: "list-group-item list-group-item-action"
   %>
  <% end %>
</div>
<%= paginate @items, remote: true %>

app/views/items/edit.html.erb
<% provide(:title, "種目の編集") %>
<h1 class="mb-3 text-center">種目の編集</h1>

<div class="row row-original">
  <div class="col-md-6 col-md-6-original">
    <%= 
      form_with model: @item,
      url: user_item_path(current_user),
      local: true do |f|
    %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="form-group">
        <%= f.label :name %>
        <%= 
          f.text_field :name,
          autofocus: true,
          autocomplete: 'name',
          class: 'form-control'
        %>
      </div>
      <div class="form-group">
        <%= f.label "メイン部位", for: 'item_part_id' %>
        <%= 
          f.collection_select :part_id, @parts, :id, :name,
          {:include_blank => true},
          {:class => "custom-select"}
        %>
      </div>
      <div class="form-group">
        <%= f.label "タイプ", for: 'item_type_id' %>
        <%= 
          f.collection_select :type_id, @types, :id, :name,
          {:include_blank => true},
          {:class => "custom-select"}
        %>
      </div>
      <div class="form-group pt-3 mb-0">
        <%= f.submit "更新", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

<div class="link-center mt-2rem">
  <i class="fas fa-angle-double-left"></i>
  <%= 
    link_to "種目へ戻る",
    user_item_path(current_user, @item),
    class: "link-center icon-edit"
  %>
</div>

app/views/items/index.html.erb
<% provide(:title, "種目一覧") %>
<h1 class="mb-3">種目一覧</h1>

<div class="link-center mb-3">
  <i class="far fa-plus-square"></i>
  <%= 
    link_to "新規作成",
    new_user_item_path,
    class: "link-center icon-edit"
  %>
</div>

<div class="parts-types select-search">
  <%=
    form_with url: user_items_search_path(current_user),
    method: :get,
    class: "search-form" do |f|
  %>
    <%= 
      f.select "parts_types", 
      @parts_types,
      {},
      class: "custom-select select-parts-types"
    %>
  <% end %>
</div>

<div id="items">
<div class="list-group list">
  <% @items.each do |item| %>
   <%= link_to item.name,
     user_item_path(current_user, item),
     class: "list-group-item list-group-item-action"
   %>
  <% end %>
</div>
<%= paginate @items, remote: true %>
</div>

app/views/items/index.js.erb
$('#items').html("<%= escape_javascript(render 'index_page') %>");

app/views/items/new.html.erb
<% provide(:title, "種目作成") %>
<h1 class="mb-3 text-center">種目作成</h1>

<div class="row row-original">
  <div class="col-md-6 col-md-6-original">
    <%= 
      form_with model: @item,
      url: user_items_path(current_user),
      local: true do |f|
    %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="form-group">
        <%= f.label :name %>
        <%= 
          f.text_field :name,
          autofocus: true,
          autocomplete: 'name',
          class: 'form-control'
        %>
      </div>
      <div class="form-group">
        <%= f.label "メイン部位", for: 'item_part_id' %>
        <%= 
          f.collection_select :part_id, @parts, :id, :name,
          {:include_blank => true},
          {:class => "custom-select"}
        %>
      </div>
      <div class="form-group">
        <%= f.label "タイプ", for: 'item_type_id' %>
        <%= 
          f.collection_select :type_id, @types, :id, :name,
          {:include_blank => true},
          {:class => "custom-select"}
        %>
      </div>
      <div class="form-group pt-3 mb-0">
        <%= f.submit "作成", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

<div class="link-center mt-2rem">
  <i class="fas fa-angle-double-left"></i>
  <%= 
    link_to "種目一覧へ戻る",
    user_items_path(current_user),
    class: "link-center icon-edit"
  %>
</div>

app/views/items/search.js.erb
$('#items').html("<%= escape_javascript(render 'index_page') %>");

app/views/items/show.html.erb
<% provide(:title, @item.name) %>
<h1 class="mb-3 text-center"><%= @item.name %></h1>

<% if @item.user_id == current_user.id %>
  <div class="link-center">
    <i class="fas fa-pencil-alt"></i>
    <%= link_to "編集",
      edit_user_item_path(current_user, @item),
      class: "link-center icon-edit"
    %>&nbsp;&nbsp;/&nbsp;<i class="far fa-minus-square"></i>
    <%= 
      link_to "種目を削除",
      user_item_path(current_user, @item),
      class: "link-center icon-reset",
      method: :delete,
      data: { confirm: "本当に種目を削除しますか？" }
    %>
  </div>
<% end %>

<table class="tbl-r02">
  <tr>
    <th>種目名</th>
    <td><%= @item.name %></td>
  </tr>
  <tr>
    <th>メイン部位</th>
    <td><%= @part.name %></td>
  </tr>
  <tr class="last">
    <th>タイプ</th>
    <td><%= @type.name %></td>
  </tr>
</table>

<div class="link-center">
  <i class="fas fa-angle-double-left"></i>
  <%= 
    link_to "種目一覧へ戻る",
    user_items_path(current_user),
    class: "link-center icon-edit"
  %>
</div>