config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'contacts#new'
  
  resources :users, only: [:index, :show]
  resources :contacts, only: [:new, :create]
  resources :users do
    get '/one_day', to: 'static_pages#one_day'
    get '/calendar', to: 'static_pages#calendar'
    get '/mon_menus', to: 'static_pages#mon_menus'
    get '/tue_menus', to: 'static_pages#tue_menus'
    get '/wed_menus', to: 'static_pages#wed_menus'
    get '/thu_menus', to: 'static_pages#thu_menus'
    get '/fri_menus', to: 'static_pages#fri_menus'
    get '/sat_menus', to: 'static_pages#sat_menus'
    get '/sun_menus', to: 'static_pages#sun_menus'
    resources :items
    get '/items_search', to: 'items#search'
    resources :menus
    resources :menus do
      resources :menu_items, only: [:index, :create]
      get 'menu_items/dynamic_items', to: 'menu_items#dynamic_items'
      delete '/menu_items', to: 'menu_items#destroy_all'
    end
    resources :week_menus, only: [:index, :create]
    delete '/week_menus', to: 'week_menus#destroy_all'
    resources :menu_records, only: [:update]
    delete '/menu_records', to: 'menu_records#destroy_all'
    resources :item_records, only: [:update]
    patch '/item_records', to: 'item_records#update_all'
  end
  
  # サンプル用の一時的なルーティング
  get '/one_day', to: 'sample_pages#one_day'
  get '/calendar', to: 'sample_pages#calendar'
  get '/mon_menus', to: 'sample_pages#mon_menus'
  get '/tue_menus', to: 'sample_pages#tue_menus'
  get '/wed_menus', to: 'sample_pages#wed_menus'
  get '/thu_menus', to: 'sample_pages#thu_menus'
  get '/fri_menus', to: 'sample_pages#fri_menus'
  get '/sat_menus', to: 'sample_pages#sat_menus'
  get '/sun_menus', to: 'sample_pages#sun_menus'
  get '/week_menus', to: 'sample_pages#week_menus'
  get '/menus', to: 'sample_pages#menus'
  get '/new_menu', to: 'sample_pages#new_menu'
  get '/menu', to: 'sample_pages#menu'
  get '/edit_menu', to: 'sample_pages#edit_menu'
  get '/menu_items', to: 'sample_pages#menu_items'
  get 'menu_items/dynamic_items', to: 'sample_pages#dynamic_items'
  get '/items', to: 'sample_pages#items'
  get '/items_search', to: 'sample_pages#search'
  get '/new_item', to: 'sample_pages#new_item'
  get '/item', to: 'sample_pages#item'
  get '/edit_item', to: 'sample_pages#edit_item'
  get '/sample_user', to: 'sample_pages#sample_user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true, length: {maximum:255}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX },
                    allow_blank: true
  validates :message, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :part
  belongs_to :type
  has_many :menu_items, dependent: :destroy
  validates :name, presence: true, length: { maximum: 30 }
  validates :user_id, presence: true
end

app/models/item_record.rb
class ItemRecord < ApplicationRecord
  belongs_to :user
  belongs_to :menu_record
  validates :name, presence: true
  validates :weight, numericality: {
                       only_integer: true,
                       greater_than: 0,
                       less_than: 1000
                     },
                     allow_blank: true
  validates :reps, numericality: {
                     only_integer: true,
                     greater_than: 0,
                     less_than: 1000
                   },
                   allow_blank: true
  validates :seconds, numericality: {
                        only_integer: true,
                        greater_than: 0,
                        less_than: 1000
                      },
                      allow_blank: true
  validates :sets, numericality: {
                     only_integer: true,
                     greater_than: 0,
                     less_than: 1000
                   },
                   allow_blank: true
  validates :date, presence: true
  validates :user_id, presence: true
  validates :menu_record_id, presence: true
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :user
  has_many :week_menus, dependent: :destroy
  has_many :menu_items, dependent: :destroy
  validates :name, presence: true, length: { maximum: 15 }
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :user
  belongs_to :menu
  belongs_to :item
  validates :user_id, presence: true
  validates :menu_id, presence: true
  validates :item_id, presence: true
  validates :weight, numericality: {
                       only_integer: true,
                       greater_than: 0,
                       less_than: 1000
                     },
                     allow_blank: true
  validates :reps, numericality: {
                     only_integer: true,
                     greater_than: 0,
                     less_than: 1000
                   },
                   allow_blank: true
  validates :seconds, numericality: {
                        only_integer: true,
                        greater_than: 0,
                        less_than: 1000
                      },
                      allow_blank: true
  validates :sets, numericality: {
                     only_integer: true,
                     greater_than: 0,
                     less_than: 1000
                   },
                   allow_blank: true                      
end

app/models/menu_record.rb
class MenuRecord < ApplicationRecord
  belongs_to :user
  has_many :item_records, dependent: :destroy
  validates :name, presence: true
  validates :date, presence: true
  validates :user_id, presence: true
end

app/models/part.rb
class Part < ApplicationRecord
  has_many :items, ->{ order(:id) }
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :items, ->{ order(:id) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_many :menus, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :week_menus, dependent: :destroy
  has_many :menu_items, dependent: :destroy
  has_many :menu_records, dependent: :destroy
  has_many :item_records, dependent: :destroy
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }
  validates :height, numericality: { less_than: 1000 },
                     allow_blank: true
  validates :body_weight, numericality: { less_than: 1000 },
                          allow_blank: true
  validates :body_fat, numericality: { less_than: 100 },
                       allow_blank: true
  validates :bench_press, numericality: {
                            only_integer: true,
                            less_than: 1000
                          },
                          allow_blank: true
  validates :squat, numericality: {
                      only_integer: true,
                      less_than: 1000
                    },
                    allow_blank: true
  validates :deadlift, numericality: {
                         only_integer: true,
                         less_than: 1000
                       },
                       allow_blank: true
end

app/models/week_menu.rb
class WeekMenu < ApplicationRecord
  belongs_to :user
  belongs_to :menu
  validates :cwday, presence: true
  validates :user_id, presence: true
  validates :menu_id, presence: true
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # ページごとの完全なタイトルを返します。
  def full_title(page_title = '')
    base_title = "WorkOut!!"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/item_records_helper.rb
module ItemRecordsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/menu_records_helper.rb
module MenuRecordsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/week_menus_helper.rb
module WeekMenusHelper
end

app/views/layouts/_flashes.html.erb
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    © 2019 WorkOut!!
  </small>
  <nav>
    <ul>
      <li><%= link_to "WorkOut!!について", about_path %></li>
      <li><%= link_to "お問い合わせ", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top">
    <div class="container">
      <%= link_to "WorkOut!!", root_path, class: "navbar-brand mb-0 h1" %>
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="Navber">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <% if current_user.admin? %>
              <li class="nav-item">
                <%= link_to "ユーザー一覧", users_path, class: "nav-link" %>
              </li>
            <% end %>
            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.name %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "スケジュール管理", user_week_menus_path(current_user), class: "dropdown-item" %>
                <%= link_to "カレンダー", user_calendar_path(current_user), class: "dropdown-item" %>
                <%= link_to "メニュー一覧", user_menus_path(current_user), class: "dropdown-item" %>
                <%= link_to "種目一覧", user_items_path(current_user), class: "dropdown-item" %>
                <%= link_to "マイページ", current_user, class: "dropdown-item" %>
                <%= link_to "アカウントの編集", edit_user_registration_path(current_user), class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "アカウント作成", new_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                サンプルページ
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "スケジュール管理", week_menus_path, class: "dropdown-item" %>
                <%= link_to "カレンダー", calendar_path, class: "dropdown-item" %>
                <%= link_to "メニュー一覧", menus_path, class: "dropdown-item" %>
                <%= link_to "種目一覧", items_path, class: "dropdown-item" %>
                <%= link_to "マイページ", sample_user_path, class: "dropdown-item" %>
              </div>
            </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
  </nav>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= stylesheet_pack_tag 'application', media: 'all' %>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
<%= javascript_pack_tag 'application' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'layouts/flashes' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= object.errors.count %>件のエラーがあります。
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>